[project]
name = "07-local-context"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openai>=1.104.0",
    "openai-agents>=0.2.10",
]
